version: '3'

services:

  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    container_name: chat-app-front
    tty: true
    volumes:
      - ./front:/app/react
    command: sh -c "cd /app/react && npm install && npm run start"
    ports:
      - 3000:3000

  go:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name:  chat-app-server
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/app/go
    command: go run .